### ISSUE TITLE
wndproc == window procedure, retard go learn c++ before pasting something new

### ISSUE THREAD

**Issue by april2202** [N3OA/based-imgui#1]
https://github.com/N3OA/based-imgui/blob/cf988215f0d64584ec792be9a594c17132047b28/src/gui/gui.cpp#L215

**Comment by N3OA** [comment]
Bro you are the retard complaining its just a example lol keep crying

**Comment by april2202** [comment]
at least he know wtf he doing not like you cant even figure out a simple mouse/kb input handling when menu is open

**Comment by april2202** [comment]
goodluck selling ur PrOgUe.SoFtWaRe lmfao

**Comment by N3OA** [comment]
The guy i sended has the same code as mee hahaah dumbass.
Also i already fixed the problem you osiris and extra paster hahaha retard kid 
Go make your shity website "This repo is for web programming class in my uni"
Keep forking projects retard paster

**Comment by april2202** [comment]
Idk who is retard paster here when u just ripped off some1 else code lmao

**Comment by april2202** [comment]
Also its nice to see some1 looking at my retard code i used for ging my classmates, I really appreciate ur reading sir

**Comment by april2202** [comment]
Oh and btw at least i forked and doing pull req sometimes not like you just ripped off it and upload ur own without any credits.... bro that's pathetic, anyway yea keep it ur way since u hate the forker like me :D (pss u can create a branch for a forked repo btw)

**Comment by N3OA** [comment]
"ripped off it and upload ur own without any credits...." Are you blind lol i gave credits axaxaxxa buy some glasses retard kid keep crying
